variables:
  - name: _BuildConfig
    value: Release
  - name: _TeamName
    value: AspNetCore
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: true
  - name: _PublishUsingPipelines
    value: true
  - name: _DotNetArtifactsCategory
    value: ENTITYFRAMEWORKCORE
  - name: _CosmosConnectionUrl
    value: https://localhost:8081
  - name: _CosmosToken
    value: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
  - name: PostBuildSign
    value: true
  - ${{ if ne(variables['System.TeamProject'], 'public') }}:
    - group: DotNet-HelixApi-Access
    - group: DotNet-MSRC-Storage
    - name: _InternalRuntimeDownloadArgs
      value: /p:DotNetRuntimeSourceFeed=https://dotnetclimsrc.blob.core.windows.net/dotnet
             /p:DotNetRuntimeSourceFeedKey=$(dotnetclimsrc-read-sas-token-base64)
  - ${{ if eq(variables['System.TeamProject'], 'public') }}:
    - name: _InternalRuntimeDownloadArgs
      value: ''

trigger:
  batch: true
  branches:
    include:
      - main
      - release/*
      - feature/*
      - internal/release/*

pr: ['*']

stages:
- stage: build
  displayName: Build
  jobs:
    - template: eng/common/templates/jobs/jobs.yml
      parameters:
        enableMicrobuild: true
        enablePublishBuildArtifacts: true
        enablePublishBuildAssets: true
        enablePublishUsingPipelines: ${{ variables._PublishUsingPipelines }}
        enableTelemetry: true
        helixRepo: dotnet/efcore
        jobs:
          - job: Helix
            timeoutInMinutes: 180
            pool:
              ${{ if eq(variables['System.TeamProject'], 'public') }}:
                name: NetCorePublic-Pool
                queue: BuildPool.Server.Amd64.VS2017.Open
              ${{ if ne(variables['System.TeamProject'], 'public') }}:
                name: NetCoreInternal-Pool
                queue: BuildPool.Server.Amd64.VS2017
            variables:
              - name: _HelixBuildConfig
                value: $(_BuildConfig)
              - ${{ if eq(variables['System.TeamProject'], 'public') }}:
                - name: HelixTargetQueues
                  value: Windows.10.Amd64.Open;Ubuntu.1804.Amd64.Open;OSX.1014.Amd64.Open
                - name: _HelixAccessToken
                  value: '' # Needed for public queues
              - ${{ if ne(variables['System.TeamProject'], 'public') }}:
                - name: HelixTargetQueues
                  value: Windows.10.Amd64;Ubuntu.1804.Amd64;OSX.1014.Amd64
                - name: _HelixAccessToken
                  value: $(HelixApiAccessToken) # Needed for internal queues
            steps:
              - task: NuGetCommand@2
                displayName: 'Clear NuGet caches'
                condition: succeeded()
                inputs:
                  command: custom
                  arguments: 'locals all -clear'
              - ${{ if ne(variables['System.TeamProject'], 'public') }}:
                - task: PowerShell@2
                  displayName: Setup Private Feeds Credentials
                  inputs:
                    filePath: $(Build.SourcesDirectory)/eng/common/SetupNugetSources.ps1
                    arguments: -ConfigFile $(Build.SourcesDirectory)/NuGet.config -Password $Env:Token
                  env:
                    Token: $(dn-bot-dnceng-artifact-feeds-rw)
              - script: restore.cmd -ci /p:configuration=$(_BuildConfig)
                displayName: Restore packages
              - script: .dotnet\dotnet build eng\helix.proj /restore /t:Test /p:configuration=$(_BuildConfig) /bl:$(Build.SourcesDirectory)/artifacts/log/$(_BuildConfig)/SendToHelix.binlog
                displayName: Send job to helix
                env:
                  HelixAccessToken: $(_HelixAccessToken)
                  SYSTEM_ACCESSTOKEN: $(System.AccessToken) # We need to set this env var to publish helix results to Azure Dev Ops
                  ACCEPT_EULA: "Y"
                  MSSQL_SA_PASSWORD: "Password12!"

- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  - template: eng\common\templates\post-build\post-build.yml
    parameters:
      publishingInfraVersion: 3
      # Symbol validation isn't being very reliable lately. This should be enabled back
      # once this issue is resolved: https://github.com/dotnet/arcade/issues/2871
      enableSymbolValidation: false
      enableSigningValidation: false
      enableNugetValidation: false
      enableSourceLinkValidation: false
